language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -U pip
  - pip install --pre pybuilder
  - pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl
  - pip install torchvision
  - pyb install_dependencies -X

script:
  - pyb run_unit_tests -X
