paths:
  videos_folder: &vidpath /data/20bn-gestures/videos_npz
  annot_folder: /data/20bn-gestures/json
  checkpoint_folder: /home/farzaneh/PycharmProjects/pytorch-captioning/checkpoint_gestures_all/

  train_annot:  /data/20bn-gestures/json/train_20170626.json.gz
  validation_annot: /data/20bn-gestures/json/validation_20170626.json.gz
  test_annot: /data/20bn-gestures/json/test_20170626.json.gz

  pretrained_path:

device:
  synchronize_gpu: &sync True
  gpus: [0]

dataloaders:
  batch_size: &b 80
  kwargs: {batch_size: *b, num_workers: 16, pin_memory: False}

model:
  type:

training:
  num_epochs: 200
  learning_rate: &lr 0.1
  teacher_force: True
  verbose: True

validation:
  frequency: 1
  teacher_force: False
  verbose: True

criteria:
  score: loss
  higher_is_better: False

