paths:
  videos_folder: &vidpath /data/20bn-gestures/frames

  annot_folder: /data/20bn-gestures/json
  train_annot:  /data/20bn-gestures/json/train_20170626.json.gz
  validation_annot: /data/20bn-gestures/json/validation_20170626.json.gz
  test_annot: /data/20bn-gestures/json/test_20170626.json.gz

device:
  use_cuda: &use_cuda True
  synchronize_gpu: &sync True
  gpus: [0]

dataloaders:
  batch_size: &b 8
  kwargs: {batch_size: *b, num_workers: 16, pin_memory: True}

model:
  type: RtorchnCaptioner
  kwargs: {use_cuda: *use_cuda}

training:
  num_epochs: 200
  learning_rate: &lr 0.01
  teacher_force: True
  verbose: True

validation:
  frequency: 1
  teacher_force: False
  verbose: True

