paths:
  videos_folder: &vidpath sample_data/videos
  annot_folder: sample_data/json
  checkpoint_folder: checkpoint_sample/

  train_annot: &train_annot sample_data/json/training_sample.json
  validation_annot: *train_annot
  test_annot: *train_annot

  pretrained_path:

device:
  synchronize_gpu: &sync True
  gpus:

dataloaders:
  batch_size: &b 2
  kwargs: {batch_size: *b, num_workers: 16, pin_memory: False}

model:
  type: RtorchnCaptioner

training:
  num_epochs: 200
  learning_rate: &lr 0.01
  teacher_force: True
  verbose: True

validation:
  frequency: 1
  teacher_force: False
  verbose: True

criteria:
  score: loss
  higher_is_better: False

