paths:
  videos_folder: &vidpath /data-ssd/20bn-somethingsomething-2017-10-31/

  checkpoint_folder: /home/farzaneh/PycharmProjects/pytorch-captioning/results/Tesssssst

  train_annot: &train_annot /data/20bn-somethingsomething/json/train_20171031.json.gz
  validation_annot: /data/20bn-somethingsomething/json/validation_20171031.json.gz
  test_annot: /data/20bn-somethingsomething/json/test_20171031.json.gz

pretrained:
  pretrained_folder:
  pretrained_file: model.best

device:
  synchronize_gpu: &sync True
  gpus: &gpus [0, 1]

dataloaders:
  kwargs: {batch_size: 16, num_workers: 8, pin_memory: False}

model:
  type: EncoderDecoder
  encoder: BIJesterEncoder
  encoder_args:
  encoder_kwargs: {pretrained_path: ,freeze: False}
  decoder: CoupledLSTMDecoder
  decoder_args:
  decoder_kwargs: {embedding_size: 256,
                   hidden_size: 1024,
                   num_lstm_layers: 2}

loss:
  caption_loss: SequenceCrossEntropy
  balanced: False
  w_caption_loss: 0.99

  classif_loss: CrossEntropy
  w_classif_loss: 0.01



optimizer:
  type: &optimizer Adam
  kwargs: {lr: 0.0001}

scheduler:
  type: ReduceLROnPlateau
  kwargs: {factor: 0.1,
           min_lr: 1.0e-8,
           optimizer: *optimizer,
           patience: 2,
           threshold: 1.0e-4}

training:
  num_epochs: 200
  clip_grad:
  teacher_force: True
  verbose: False

validation:
  frequency: 1
  teacher_force: True
  verbose: True

criteria:
  score: caption_accuracy
  higher_is_better: True

targets:
  caption_type: template

tokenizer:
  kwargs: {user_maxlen: 13, cutoff: 5}

logging:
  verbose: True
  tensorboard_frequency: 1000

preprocess:
  crop_size: [48, 96, 96]
  scale: 64.
  input_resize: [128, 128]
