paths:
  videos_folder: &vidpath /data-ssd/videos_gulp/

  checkpoint_folder: /home/farzaneh/PycharmProjects/pytorch-captioning/results/jester1024_dividing/

  train_annot: &train_annot /data/20bn-somethingsomething/json/train_20170929.json.gz
  validation_annot: /data/20bn-somethingsomething/json/validation_20170929.json.gz
  test_annot: /data/20bn-somethingsomething/json/test_20170929.json.gz

pretrained:
  pretrained_folder:
  pretrained_file: model.latest

device:
  synchronize_gpu: &sync True
  gpus: &gpus [0]

dataloaders:
  kwargs: {batch_size: 16, num_workers: 16, pin_memory: False}

model:
  type: EncoderDecoder
  encoder: BIJesterEncoder
  encoder_args:
  encoder_kwargs: {pretrained_path: /home/farzaneh/PycharmProjects/pretrained_nets/jester_net_on_smtsmt_official_1024/model.checkpoint,
                   freeze: True}
  decoder: LSTMDecoder
  decoder_args:
  decoder_kwargs: {embedding_size: 256,
                   hidden_size: 1024,
                   num_lstm_layers: 1}

loss:
  type: SequenceCrossEntropy

optimizer:
  type: &optimizer Adam
  kwargs: {lr: 0.001}

scheduler:
  type: ReduceLROnPlateau
  kwargs: {factor: 0.1,
           min_lr: 1.0e-8,
           optimizer: *optimizer,
           patience: 3,
           threshold: 1.0e-4}

training:
  num_epochs: 200
  clip_grad:
  teacher_force: True
  verbose: False

validation:
  frequency: 1
  teacher_force: True
  verbose: True

criteria:
  score: accuracy
  higher_is_better: True

targets:
  caption_type: template

tokenizer:
  kwargs: {user_maxlen: 13, cutoff: 300}

logging:
  verbose: True
  tensorboard_frequency: 1000

