paths:
  videos_folder: &vidpath /data/20bn-objects/videos_npz
  checkpoint_folder: /home/waseem/Models

  train_annot: &train_annot /data/20bn-objects/json/train_20170429.json.gz
  validation_annot: /data/20bn-objects/json/validation_20170429.json.gz
  test_annot: /data/20bn-objects/json/test_20170429.json.gz

pretrained:
  pretrained_folder:
  pretrained_file:

device:
  synchronize_gpu: &sync True
  gpus: &gpus [0]

dataloaders:
  kwargs: {batch_size: 16, num_workers: 16, pin_memory: False}

model:
  type: EncoderDecoder
  encoder: CNN3dEncoder
  encoder_args:
  encoder_kwargs: {encoder_output_size: &encoder_output_size 1024}
  decoder: LSTMDecoder
  decoder_args:
  decoder_kwargs: {embedding_size: 256,
                   hidden_size: *encoder_output_size,
                   num_lstm_layers: 1}

loss:
  type: SequenceCrossEntropy

optimizer:
  type: &optimizer Adam
  kwargs: {lr: 1.0e-4}

scheduler:
  type: ReduceLROnPlateau
  kwargs: {factor: 0.1,
           min_lr: 1.0e-8,
           optimizer: *optimizer,
           patience: 2,
           threshold: 1.0e-4}

training:
  num_epochs: 200
  clip_grad: 1
  teacher_force: True
  verbose: False

validation:
  frequency: 1
  teacher_force: True
  verbose: True

criteria:
  score: loss
  higher_is_better: False

targets:
  caption_type: label

tokenizer:
  kwargs: {user_maxlen: 10}

logging:
  verbose: True
  tensorboard_frequency: 1000