paths:
  videos_folder: &vidpath /data/20bn-objects/videos_npz
  checkpoint_folder: /home/farzaneh/PycharmProjects/pytorch-captioning/results/ckp_sth_exp_frozen_pret/

  train_annot: &train_annot /data/20bn-objects/json/train_20170630.json.gz
  validation_annot: /data/20bn-objects/json/validation_20170630.json.gz
  test_annot: /data/20bn-objects/json/test_20170630.json.gz

pretrained:
  pretrained_folder:
  pretrained_file:

device:
  synchronize_gpu: &sync True
  gpus: &gpus [0]

dataloaders:
  kwargs: {batch_size: 16, num_workers: 16, pin_memory: False}

model:
  type: EncoderDecoder
  encoder: RtorchnEncoderP
  encoder_kwargs: {pretrained_path: /home/farzaneh/PycharmProjects/pretrained_nets/fully_conv_net_on_smtsmt_20170627/model.checkpoint,
                   freeze: False,
                   encoder_output_size: &enc_out_size 256,
                   num_classes: 178}
  decoder: LSTMDecoder
  decoder_kwargs: {embedding_size: 256,
                   hidden_size: *enc_out_size,
                   num_lstm_layers: 1}

loss:
  type: SequenceCrossEntropy

optimizer:
  type: &optimizer Adam
  kwargs: {lr: 0.01}

scheduler:
  type: ReduceLROnPlateau
  kwargs: {factor: 0.1,
           min_lr: 1e-8,
           optimizer: *optimizer,
           patience: 3,
           threshold: 1e-4}

training:
  num_epochs: 2
  clip_grad: 1
  teacher_force: True
  verbose: False

validation:
  frequency: 1
  teacher_force: False
  verbose: True

criteria:
  score: loss
  higher_is_better: False

targets:
  caption_type: label

tokenizer:
  kwargs: {user_maxlen: 10}

logging:
  verbose: True
  tensorboard_frequency: 1