paths:
  videos_folder: &vidpath /data-ssd/v2-gulp-160/

  checkpoint_folder: /home/farzaneh/PycharmProjects/pytorch-captioning/results/july_classif_r_penalty_0_cross_entropy_reward

  pretrained_file: model.best

  train_annot: &train_annot /data/20bn-something-something-v2-annotations/v2-train.json
  validation_annot: /data/20bn-something-something-v2-annotations/v2-validation.json
  test_annot: /data/20bn-something-something-v2/v2-test.json


pretrained:
  pretrained_path:
  pretrained_encoder_path: "/home/farzaneh/PycharmProjects/pytorch-captioning/results/Causal/v2_gulp160_causal_labels_cutoff5_classif0.9_cap0.1/model.best"
  pretrained_decoder_path: "/home/farzaneh/PycharmProjects/pytorch-captioning/results/Causal/v2_gulp160_causal_labels_cutoff5_classif0.9_cap0.1/model.best"

  load_encoder_only: True

device:
  synchronize_gpu: &sync True
  gpus: &gpus [0, 1]

dataloaders:
  kwargs: {batch_size: 16, num_workers: 8, pin_memory: False}

model:
  type: EncoderDecoder
  encoder: C3dLSTMEncoder
  encoder_args:
  encoder_kwargs: {encoder_output_size: 1024,
                   rnn_output_size: 512}
  decoder: CoupledLSTMDecoder
  decoder_args:
  decoder_kwargs: {embedding_size: 256,
                   hidden_size: 1024,
                   num_lstm_layers: 2,
                   fc_size: 1024,
                   num_step: 1}

loss:
  caption_loss: SequenceCrossEntropy
  balanced: False
  w_caption_loss: 0

  classif_loss: CrossEntropy
  w_classif_loss: 1



optimizer:
  type: &optimizer Adam
  kwargs: {lr: 0.00001}

scheduler:
  type: ReduceLROnPlateau
  kwargs: {factor: 0.1,
           min_lr: 1.0e-8,
           optimizer: *optimizer,
           patience: 2,
           threshold: 1.0e-4}

training:
  num_epochs: 200
  clip_grad:
  teacher_force: True
  verbose: False

validation:
  frequency: 1
  teacher_force: False
  verbose: True

criteria:
  score: classif_accuracy
  higher_is_better: True

targets:
  caption_type: template

tokenizer:
  kwargs: {user_maxlen: 13, cutoff: 5}

logging:
  verbose: True
  tensorboard_frequency: 1

preprocess:
  crop_size: [48, 96, 96]
  scale: 64.
  input_resize: [128, 128]

reinforce:
  correct_w_reward: 0.1
  correct_r_reward: 0
  incorrect_w_reward: -0.1
  incorrect_r_reward: -1