paths:
  videos_folder: &vidpath /data-ssd/v2-gulp-160/

  checkpoint_folder: /home/farzaneh/PycharmProjects/pytorch-captioning/results/v2_gulp160_labels_classif0.01_cap0.99


  train_annot: &train_annot /data-ssd/v2-train.json
  validation_annot: /data-ssd/v2-validation.json
  test_annot: /data/20bn-something-something-v2/v2-validation.json


pretrained:
  pretrained_folder: /home/farzaneh/PycharmProjects/pytorch-captioning/results/v2_gulp160_labels_classif0.1_cap0.9
  pretrained_file: model.best

device:
  synchronize_gpu: &sync True
  gpus: &gpus [0, 1]

dataloaders:
  kwargs: {batch_size: 12, num_workers: 8, pin_memory: False}

model:
  type: EncoderDecoder
  encoder: BIJesterEncoder
  encoder_args:
  encoder_kwargs: {pretrained_path: , freeze: False}
  decoder: CoupledLSTMDecoder
  decoder_args:
  decoder_kwargs: {embedding_size: 256,
                   hidden_size: 512,
                   num_lstm_layers: 2}

loss:
  caption_loss: SequenceCrossEntropy
  balanced: False
  w_caption_loss: 0.99

  classif_loss: CrossEntropy
  w_classif_loss: 0.01



optimizer:
  type: &optimizer Adam
  kwargs: {lr: 0.0001}

scheduler:
  type: ReduceLROnPlateau
  kwargs: {factor: 0.1,
           min_lr: 1.0e-8,
           optimizer: *optimizer,
           patience: 2,
           threshold: 1.0e-4}

training:
  num_epochs: 200
  clip_grad:
  teacher_force: True
  verbose: False

validation:
  frequency: 1
  teacher_force: True
  verbose: True

criteria:
  score: caption_accuracy
  higher_is_better: True

targets:
  caption_type: label

tokenizer:
  kwargs: {user_maxlen: 13, cutoff: 5}

logging:
  verbose: True
  tensorboard_frequency: 1000

preprocess:
  crop_size: [48, 128, 128]
  scale: 64.
  input_resize: [160, 160]
