paths:
  videos_folder: &vidpath /data-ssd/videos_gulp/
  checkpoint_folder: /home/farzaneh/PycharmProjects/pytorch-captioning/results/subset_sth_fc_unfrozen/

  train_annot:  /home/farzaneh/PycharmProjects/pytorch-captioning/src/main/python/scripts/subset_train_20170929.json.gz
  validation_annot: /home/farzaneh/PycharmProjects/pytorch-captioning/src/main/python/scripts/subset_validation_20170929.json.gz
  test_annot: /home/farzaneh/PycharmProjects/pytorch-captioning/src/main/python/scripts/subset_test_20170929.json.gz

pretrained:
  pretrained_folder:
  pretrained_file: model.latest

device:
  synchronize_gpu: &sync True
  gpus: &gpus [0]

dataloaders:
  kwargs: {batch_size: 10, num_workers: 8, pin_memory: False}

model:
  type: EncoderDecoder
  encoder2: FCEncoder
  encoder_args:
  encoder_kwargs2: {pretrained_path: /home/farzaneh/PycharmProjects/pretrained_nets/fully_conv_net_on_smtsmt_20170627/model.checkpoint,
                   freeze: False}

  encoder: CNN3dLSTMEncoder
  encoder_kwargs: {encoder_output_size: 256, gpus: *gpus}


  decoder: LSTMDecoder
  decoder_args:
  decoder_kwargs: {embedding_size: 256,
                   hidden_size: 256,
                   num_lstm_layers: 1}

loss:
  type: SequenceCrossEntropy

optimizer:
  type: &optimizer Adam
  kwargs: {lr: 0.001}

scheduler:
  type: ReduceLROnPlateau
  kwargs: {factor: 0.1,
           min_lr: 1.0e-8,
           optimizer: *optimizer,
           patience: 3,
           threshold: 1.0e-4}

training:
  num_epochs: 200
  clip_grad:
  teacher_force: True
  verbose: False

validation:
  frequency: 100
  teacher_force: False
  verbose: True

criteria:
  score: accuracy
  higher_is_better: True

targets:
  caption_type: template

tokenizer:
  kwargs: {user_maxlen: 13, cutoff: 2}

logging:
  verbose: True
  tensorboard_frequency: 1000

