paths:
  videos_folder: &vidpath /data/20bn-gestures/frames

  annot_folder: /data/20bn-gestures/json
  train_annot: &train_annot /data/20bn-gestures/json/train_20170626.json.gz
  validation_annot: *train_annot
  test_annot: *train_annot

device:
  use_cuda: &use_cuda False
  synchronize_gpu: &sync True
  gpus: [0]

dataloaders:
  batch_size: &b 16
  kwargs: {batch_size: *b, num_workers: 16, pin_memory: True}

model:
  type: RtorchnCaptioner
  kwargs: {use_cuda: *use_cuda}

training:
  num_epochs: 200
  learning_rate: &lr 0.01
  valid_frequency: 1

