class_num_2_label={
 0: 'Approaching [something] with your camera',
 1: 'Attaching [something] to [something]',
 2: 'Bending [something] so that it deforms',
 3: 'Bending [something] until it breaks',
 4: 'Burying [something] in [something]',
 5: 'Closing [something]',
 6: 'Covering [something] with [something]',
 7: 'Digging [something] out of [something]',
 8: 'Dropping [something] behind [something]',
 9: 'Dropping [something] in front of [something]',
 10: 'Dropping [something] into [something]',
 11: 'Dropping [something] next to [something]',
 12: 'Dropping [something] onto [something]',
 13: 'Failing to put [something] into [something] because [something] does not fit',
 14: 'Folding [something]',
 15: 'Hitting [something] with [something]',
 16: 'Holding [something]',
 17: 'Holding [something] behind [something]',
 18: 'Holding [something] in front of [something]',
 19: 'Holding [something] next to [something]',
 20: 'Holding [something] over [something]',
 21: 'Laying [something] on the table on its side, not upright',
 22: 'Letting [something] roll along a flat surface',
 23: 'Letting [something] roll down a slanted surface',
 24: 'Letting [something] roll up a slanted surface, so it rolls back down',
 25: 'Lifting [something] up completely without letting it drop down',
 26: 'Lifting [something] up completely, then letting it drop down',
 27: 'Lifting [something] with [something] on it',
 28: 'Lifting a surface with [something] on it but not enough for it to slide down',
 29: 'Lifting a surface with [something] on it until it starts sliding down',
 30: 'Lifting up one end of [something] without letting it drop down',
 31: 'Lifting up one end of [something], then letting it drop down',
 32: 'Moving [part] of [something]',
 33: 'Moving [something] across a surface until it falls down',
 34: 'Moving [something] across a surface without it falling down',
 35: 'Moving [something] and [something] away from each other',
 36: 'Moving [something] and [something] closer to each other',
 37: 'Moving [something] and [something] so they collide with each other',
 38: 'Moving [something] and [something] so they pass each other',
 39: 'Moving [something] away from [something]',
 40: 'Moving [something] away from the camera',
 41: 'Moving [something] closer to [something]',
 42: 'Moving [something] down',
 43: 'Moving [something] towards the camera',
 44: 'Moving [something] up',
 45: 'Moving away from [something] with your camera',
 46: 'Opening [something]',
 47: 'Picking [something] up',
 48: 'Piling [something] up',
 49: 'Plugging [something] into [something]',
 50: 'Plugging [something] into [something] but pulling it right out as you remove your hand',
 51: 'Poking [something] so it slightly moves',
 52: "Poking [something] so lightly that it doesn't or almost doesn't move",
 53: 'Poking [something] so that it falls over',
 54: 'Poking [something] so that it spins around',
 55: 'Poking a hole into [some substance]',
 56: 'Poking a hole into [something soft]',
 57: 'Poking a stack of [something] so the stack collapses',
 58: 'Poking a stack of [something] without the stack collapsing',
 59: 'Pouring [something] into [something]',
 60: 'Pouring [something] into [something] until it overflows',
 61: 'Pouring [something] onto [something]',
 62: 'Pouring [something] out of [something]',
 63: 'Pretending or failing to wipe [something] off of [something]',
 64: 'Pretending or trying and failing to twist [something]',
 65: 'Pretending to be tearing [something that is not tearable]',
 66: 'Pretending to close [something] without actually closing it',
 67: 'Pretending to open [something] without actually opening it',
 68: 'Pretending to pick [something] up',
 69: 'Pretending to poke [something]',
 70: 'Pretending to pour [something] out of [something], but [something] is empty',
 71: 'Pretending to put [something] behind [something]',
 72: 'Pretending to put [something] into [something]',
 73: 'Pretending to put [something] next to [something]',
 74: 'Pretending to put [something] on a surface',
 75: 'Pretending to put [something] onto [something]',
 76: 'Pretending to put [something] underneath [something]',
 77: 'Pretending to scoop [something] up with [something]',
 78: 'Pretending to spread air onto [something]',
 79: 'Pretending to sprinkle air onto [something]',
 80: 'Pretending to squeeze [something]',
 81: 'Pretending to take [something] from [somewhere]',
 82: 'Pretending to take [something] out of [something]',
 83: 'Pretending to throw [something]',
 84: 'Pretending to turn [something] upside down',
 85: 'Pulling [something] from behind of [something]',
 86: 'Pulling [something] from left to right',
 87: 'Pulling [something] from right to left',
 88: 'Pulling [something] onto [something]',
 89: 'Pulling [something] out of [something]',
 90: 'Pulling two ends of [something] but nothing happens',
 91: 'Pulling two ends of [something] so that it gets stretched',
 92: 'Pulling two ends of [something] so that it separates into two pieces',
 93: 'Pushing [something] from left to right',
 94: 'Pushing [something] from right to left',
 95: 'Pushing [something] off of [something]',
 96: 'Pushing [something] onto [something]',
 97: 'Pushing [something] so it spins',
 98: "Pushing [something] so that it almost falls off but doesn't",
 99: 'Pushing [something] so that it falls off the table',
 100: 'Pushing [something] so that it slightly moves',
 101: 'Pushing [something] with [something]',
 102: 'Putting [number of] [something] onto [something]',
 103: 'Putting [something similar to other things that are already on the table]',
 104: 'Putting [something that cannot actually stand upright] upright on the table, so it falls on its side',
 105: 'Putting [something] and [something] on the table',
 106: 'Putting [something] behind [something]',
 107: 'Putting [something] in front of [something]',
 108: 'Putting [something] into [something]',
 109: 'Putting [something] next to [something]',
 110: 'Putting [something] on a flat surface without letting it roll',
 111: 'Putting [something] on a surface',
 112: 'Putting [something] on the edge of [something] so it is not supported and falls down',
 113: 'Putting [something] onto [something else that cannot support it] so it falls down',
 114: 'Putting [something] onto [something]',
 115: "Putting [something] onto a slanted surface but it doesn't glide down",
 116: "Putting [something] that can't roll onto a slanted surface, so it slides down",
 117: "Putting [something] that can't roll onto a slanted surface, so it stays where it is",
 118: 'Putting [something] underneath [something]',
 119: 'Putting [something] upright on the table',
 120: 'Putting [something], [something] and [something] on the table',
 121: 'Removing [something], revealing [something] behind',
 122: 'Rolling [something] on a flat surface',
 123: 'Scooping [something] up with [something]',
 124: 'Showing [something] behind [something]',
 125: 'Showing [something] next to [something]',
 126: 'Showing [something] on top of [something]',
 127: 'Showing [something] to the camera',
 128: 'Showing a photo of [something] to the camera',
 129: 'Showing that [something] is empty',
 130: 'Showing that [something] is inside [something]',
 131: 'Spilling [something] behind [something]',
 132: 'Spilling [something] next to [something]',
 133: 'Spilling [something] onto [something]',
 134: 'Spinning [something] so it continues spinning',
 135: 'Spinning [something] that quickly stops spinning',
 136: 'Spreading [something] onto [something]',
 137: 'Sprinkling [something] onto [something]',
 138: 'Squeezing [something]',
 139: 'Stacking [number of] [something]',
 140: 'Stuffing [something] into [something]',
 141: 'Taking [one of many similar things on the table]',
 142: 'Taking [something] from [somewhere]',
 143: 'Taking [something] out of [something]',
 144: 'Tearing [something] into two pieces',
 145: 'Tearing [something] just a little bit',
 146: 'Throwing [something]',
 147: 'Throwing [something] against [something]',
 148: 'Throwing [something] in the air and catching it',
 149: 'Throwing [something] in the air and letting it fall',
 150: 'Throwing [something] onto a surface',
 151: "Tilting [something] with [something] on it slightly so it doesn't fall down",
 152: 'Tilting [something] with [something] on it until it falls off',
 153: 'Tipping [something] over',
 154: 'Tipping [something] with [something in it] over, so [something in it] falls out',
 155: 'Touching (without moving) [part] of [something]',
 156: "Trying but failing to attach [something] to [something] because it doesn't stick",
 157: 'Trying to bend [something unbendable] so nothing happens',
 158: 'Trying to pour [something] into [something], but missing so it spills next to it',
 159: 'Turning [something] upside down',
 160: 'Turning the camera downwards while filming [something]',
 161: 'Turning the camera left while filming [something]',
 162: 'Turning the camera right while filming [something]',
 163: 'Turning the camera upwards while filming [something]',
 164: 'Twisting (wringing) [something] wet until water comes out',
 165: 'Twisting [something]',
 166: 'Uncovering [something]',
 167: 'Unfolding [something]',
 168: 'Wiping [something] off of [something]',
 169: '[Something] being deflected from [something]',
 170: '[Something] colliding with [something] and both are being deflected',
 171: '[Something] colliding with [something] and both come to a halt',
 172: '[Something] falling like a feather or paper',
 173: '[Something] falling like a rock'}