criteria: {higher_is_better: false, score: loss}
dataloaders:
  batch_size: 16
  kwargs: {batch_size: 16, num_workers: 16, pin_memory: true}
device:
  gpus: [0]
  synchronize_gpu: true
loss: {type: SequenceCrossEntropy}
model:
  kwargs: {}
  type: CNN3dLSTM
optimizer: {type: Adam}
paths: {annot_folder: /data/20bn-objects/json, checkpoint_folder: /home/farzaneh/PycharmProjects/pytorch-captioning/ckp_sth_templates_25ep/,
  pretrained_path: null, test_annot: /data/20bn-gestures/json/test_20170429.json.gz,
  train_annot: /data/20bn-objects/json/train_20170429.json.gz, validation_annot: /data/20bn-objects/json/validation_20170429.json.gz,
  videos_folder: /data/20bn-objects/videos_npz}
targets: {caption_type: template, user_maxlen: 10}
training: {learning_rate: 0.01, num_epochs: 200, teacher_force: true, verbose: false}
validation: {frequency: 5, teacher_force: false, verbose: true}
